#!/usr/bin/env python3
from __future__ import annotations
"""Interview-driven USER.md scaffolding + Anthropic-compatible prompt generator."""

import argparse
import datetime as dt
import os
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[1]

QUESTIONS = [
    ("user_name", "User display name", "USER_NAME"),
    ("assistant_name", "Assistant display name", "ASSISTANT_NAME"),
    ("workspace_name", "Workspace name", "WORKSPACE_NAME"),
    ("timezone", "Timezone", "Asia/Tokyo"),
    ("wake_time", "Usual wake time", "07:30"),
    ("sleep_time", "Usual sleep time", "23:30"),
    ("quiet_hours", "Quiet hours", "22:30-07:30"),
    ("work_start", "Work start time", "09:30"),
    ("work_end", "Work end time", "18:30"),
    ("interests", "Interests, comma separated", "reading, fitness, software"),
    ("daily_brief_time", "Daily brief time", "08:00"),
    ("calendar_reminder", "Calendar reminder minutes", "30,5"),
    ("discord_channel", "Default Discord channel id/name", "general"),
    ("notion_usage", "Use Notion? yes/no", "yes"),
    ("google_calendar", "Use Google Calendar? yes/no", "no"),
]

def ask(key: str, label: str, default: str) -> str:
    raw = input(f"{label} [{default}]: ").strip()
    return raw or default

def render_user_md(values: dict[str, str]) -> str:
    now = dt.datetime.now().isoformat(timespec="seconds")
    return dedent(f"""\
    # USER

    Generated by `scripts/onboarding.py` at {now}.

    ## Identity

    - User: {values["user_name"]}
    - Assistant: {values["assistant_name"]}
    - Workspace: {values["workspace_name"]}
    - Timezone: {values["timezone"]}

    ## Daily Rhythm

    - Wake time: {values["wake_time"]}
    - Sleep time: {values["sleep_time"]}
    - Quiet hours: {values["quiet_hours"]}
    - Work hours: {values["work_start"]}-{values["work_end"]}
    - Daily brief: {values["daily_brief_time"]}

    ## Preferences

    - Interests: {values["interests"]}
    - Calendar reminders: {values["calendar_reminder"]} minutes before events
    - Default Discord channel: {values["discord_channel"]}
    - Notion enabled: {values["notion_usage"]}
    - Google Calendar enabled: {values["google_calendar"]}

    ## Privacy Rule

    Keep private details out of public repositories. Use placeholders such as
    `USER_NAME`, `ASSISTANT_NAME`, `WORKSPACE_NAME`, `DISCORD_CHANNEL_ID`,
    `NOTION_DATABASE_ID`, and `GOOGLE_CALENDAR_ID` in shareable files.
    """)

def render_prompt(values: dict[str, str]) -> str:
    return dedent(f"""\
    You are {values["assistant_name"]}, a personal assistant for {values["user_name"]}.

    Workspace: {values["workspace_name"]}
    Timezone: {values["timezone"]}

    Operating preferences:
    - Respect quiet hours: {values["quiet_hours"]}.
    - Prepare daily brief around {values["daily_brief_time"]}.
    - Remind calendar events {values["calendar_reminder"]} minutes before start.
    - Prefer concise, actionable responses.
    - Ask before using external APIs that require credentials.

    Feature proposal checklist:
    1. Daily brief
    2. Task digest
    3. Calendar reminders
    4. Memory capture
    5. Discord log sync
    6. Health ping
    7. Recommendation digest

    If an API key is required, explain the exact `.env` variable name and ask the
    user to paste it manually. Do not invent or request secrets in chat history.
    """)

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--agent-dir", default="AGENT")
    parser.add_argument("--yes", action="store_true")
    args = parser.parse_args()

    values = {}
    print("Interactive onboarding. Press Enter to accept defaults.")
    for key, label, default in QUESTIONS:
        values[key] = default if args.yes else ask(key, label, default)

    agent_dir = ROOT / args.agent_dir
    prompt_dir = ROOT / "templates" / "generated"
    agent_dir.mkdir(parents=True, exist_ok=True)
    prompt_dir.mkdir(parents=True, exist_ok=True)

    user_md = agent_dir / "USER.md"
    prompt_md = prompt_dir / "anthropic_compatible_prompt.md"

    if user_md.exists() and not args.yes:
        ok = input(f"{user_md} exists. Overwrite? [y/N]: ").strip().lower()
        if ok != "y":
            print("cancelled")
            return 1

    user_md.write_text(render_user_md(values), encoding="utf-8")
    prompt_md.write_text(render_prompt(values), encoding="utf-8")

    print(f"wrote {user_md}")
    print(f"wrote {prompt_md}")
    print("Next: copy `.env.template` to `.env` and paste required API keys manually.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
