#!/usr/bin/env python3
from __future__ import annotations
"""Bootstrap the 8 Phase-1 Notion DBs under a given parent page."""

import argparse
import json
import os
import sys
from pathlib import Path

import requests
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[3]
SCHEMA_DIR = ROOT / "notion_schemas"
OUT_ENV = ROOT / ".env.generated.notion"
NOTION_API = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"

load_dotenv(ROOT / ".env")

def headers() -> dict[str, str]:
    token = os.environ.get("NOTION_TOKEN", "")
    if not token:
        raise RuntimeError("NOTION_TOKEN is required")
    return {
        "Authorization": f"Bearer {token}",
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
    }

def load_schema(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))

def create_database(parent_page_id: str, schema_path: Path) -> tuple[str, str]:
    schema = load_schema(schema_path)
    title = schema["title"]
    body = {
        "parent": {"type": "page_id", "page_id": parent_page_id},
        "title": [{"type": "text", "text": {"content": title}}],
        "properties": schema["properties"],
    }
    response = requests.post(f"{NOTION_API}/databases", headers=headers(), json=body, timeout=30)
    if response.status_code not in (200, 201):
        raise RuntimeError(f"{schema_path.name}: HTTP {response.status_code}: {response.text[:500]}")
    return schema["env"], response.json()["id"]

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--parent-page-id", default=os.environ.get("NOTION_PARENT_PAGE_ID", ""))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.parent_page_id:
        print("NOTION_PARENT_PAGE_ID is required", file=sys.stderr)
        return 1

    schema_paths = sorted(SCHEMA_DIR.glob("*.json"))
    if args.dry_run:
        for path in schema_paths:
            schema = load_schema(path)
            print(f"would create: {schema['title']} -> {schema['env']}")
        return 0

    lines = ["# Generated by scripts/integrations/notion/create_databases.py"]
    for path in schema_paths:
        env_key, db_id = create_database(args.parent_page_id, path)
        lines.append(f"{env_key}={db_id}")
        print(f"created {env_key}={db_id}")

    OUT_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_ENV}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
